version: '3.3'
services:
  api:
    image: qfund.api
    container_name: qfund-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5050:5050"
      - "5051:5051"
  db:
    image: postgres:latest
    container_name: qfund-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qfund_local
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq:management
    container_name: qfund-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - rabbitmq
volumes:
  db:
    driver: local

networks:
  rabbitmq:
    driver: bridge
