version: '3.3'
services:
  db:
    image: 'postgres:latest'
    container_name: qfund-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qfund_local
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes: 
  db:
    driver: local
