version: '3.3'
services:
  db:
    image: postgres:latest
    container_name: qfund-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qfund_local
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: qfund-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks: 
      - rabbitmq
volumes:
  db:
    driver: local
    
networks:
  rabbitmq:
    driver: bridge
