version: '3.8'
services:
  qfund-api:
    build:
      context: .
      dockerfile: ../Dockerfile
  qfund-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qfund_local
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  qfund-rabbit:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
volumes:
  db:
    driver: local

